# Change these first
owner: flaxton # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: cloud01
    url: https://cloud01.infotechdesign.ws
  - name: cloud02
    url: http://cloud02.infotechdesign.ws:8090
  - name: cloud03
    url: http://vpn.blueridgecs.com/
  - name: cloud04
    url: https://cloud04.infotechdesign.ws
  - name: cloud05
    url: https://cloud05.infotechdesign.ws
  - name: cloud06
    url: https://cloud06.infotechdesign.ws
  - name: GWC
    url: https://genwealthconcepts.com
  - name: The Money Multiplier
    url: https://themoneymultiplier.com
#  - name: Google
#    url: https://www.google.com
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Test for HEAD
#    method: HEAD
#    url: https://www.google.com
#  - name: Secret Site
#    url: $SECRET_SITE
#  - name: TCP ping
#    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**InfoTechDesign LLC Service Status**"
  introMessage: Following are service status and other important information
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
