# Change these first
owner: flaxton # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: cloud01
    url: http://cloud01.infotechdesign.ws
  - name: cloud02
    url: http://cloud02.infotechdesign.ws:8090
  - name: cloud03
    url: http://vpn.blueridgecs.com/
  - name: cloud04
    url: http://cloud04.infotechdesign.ws
  - name: cloud05
    url: https://cloud05.infotechdesign.ws
  - name: cloud06
    url: https://cloud06.infotechdesign.ws
  - name: GWC
#    url: $SECRET_SITE1
    url: https://genwealthconcepts.com
  - name: TMM
    url: https://themoneymultiplier.com
#  - name: Google
#    url: https://www.google.com
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Test for HEAD
#    method: HEAD
#    url: https://www.google.com
#  - name: Secret Site
#    url: $SECRET_SITE
#  - name: TCP ping
#    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://infotechdesign.org/wp-content/uploads/2020/10/itd_s5_logo-334x64-1.png
#  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime / Status
  introTitle: "**InfoTechDesign LLC Service Status**"
  introMessage: Following are service status and other important information
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

env:
#  NOTIFICATION_SLACK: ${{ secrets.NOTIFICATION_SLACK }} 
#  NOTIFICATION_SLACK_WEBHOOK: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK }} 
#  NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}
  NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
  NOTIFICATION_EMAIL_FROM: ${{ secrets.NOTIFICATION_EMAIL_FROM }}
  NOTIFICATION_EMAIL_SENDGRID: ${{ secrets.NOTIFICATION_EMAIL_SENDGRID }}
  NOTIFICATION_EMAIL_SENDGRID_API_KEY: ${{ NOTIFICATION_EMAIL_SENDGRID_API_KEY }}
  NOTIFICATION_EMAIL_TO: ${{ NOTIFICATION_EMAIL_TO }}




